name: Test

on:
  push:
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@main
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
